### ISSUE TITLE
When running without parameters, prisma cli should display the help

### ISSUE THREAD

**Issue by dlight** [Brendonovich/prisma-client-rust#139]
Here I have in `.cargo/config.toml`:

```toml
[alias]
prisma = "run --quiet --package cli --"
```

When I run `cargo prisma --help` or `cargo prisma migrate dev`, things work. But if I run just `cargo prisma`, it outputs a confusing error message:

```console
$ cargo prisma
This command is only meant to be invoked internally. Please specify a command to run.
```

It should, instead, display the same was `cargo prisma --help`.
