### ISSUE TITLE
prisma generate report 'Error: (query-engine binary)' on Amazon Linux 2023

### ISSUE THREAD

**Issue by chensoft** [Brendonovich/prisma-client-rust#462]
## Issue

Hello, I have encountered an issue when I call `prisma generate` on Amazon Linux 2023. It reports the following error:

```
Prisma schema loaded from prisma/schema.prisma
Error: (query-engine binary)
Details: 
[Context: getDmmf]

Prisma CLI Version : 4.8.0
```

## Environment

- OS: Amazon Linux 2023 AMI 2023.4.20240611.0 x86_64 HVM kernel-6.1
- Arch: 64-bit x86
- Machine: c5.2xlarge
- Rust: 1.79.0

### Cargo.toml

```toml
[package]
name = "prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
```

### src/main.rs

```rust
fn main() {
    prisma_client_rust_cli::run();
}
```

### prisma/schema.prisma

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "cargo prisma"
  output   = "schema.rs"
}

model users {
  user_id String @id
}
```

### ~/.cargo/config.toml

```toml
[alias]
prisma='run --'
```

## Steps

Just run `cargo prisma generate`.

Could you help me to look at this problem? Thank you!
