### ISSUE TITLE
DB connection error on 0.5.1

### ISSUE THREAD

**Issue by Suyashtnt** [Brendonovich/prisma-client-rust#77]
On 0.5.0, my app works fine. However when upgrading to 0.5.1, I get this error:
```
❯ docker logs -f discord-chess-bot-1
2022-06-06T17:10:00.775898Z  INFO exec_loader{features=[] url="postgresql://postgres:postgres@localhost:5432/DiscordChess?schema=public"}: quaint::pooled: Starting a postgresql pool with 17 connections.
Error: Error getting database connection: Error creating a database connection. (Error creating a database connection.)

Caused by:
    Error creating a database connection. (Error creating a database connection.)
```
As you can see I am using docker here so maybe that's a part of the issue. I made sure I ran `prisma migrate dev` before rerunning the bot

docker script:
```yaml
version: "3"

networks:
  main:

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - main
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    env_file:
      - "env.influxdb"
    volumes:
      - influx-data:/var/lib/influxdb

  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/config/loki.yml
    volumes:
      - "./loki.yml:/etc/config/loki.yml"
    networks:
      - main

  grafana:
    image: grafana/grafana:latest
    user: "0"
    ports:
      - "3000:3000"
    env_file:
      - env.grafana
    networks:
      - main
    links:
      - influxdb
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana

  bot:
    build: .
    ports:
      - "6669:6669"
    volumes:
      - /home/root/.cargo
    depends_on:
      - postgres
      - loki
      - influxdb
      - grafana
    networks:
      - main
    env_file:
      - env.bot

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    networks:
      - main
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DiscordChess
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  cargo:
  target:
  postgres-data:
  influx-data:
```

prisma schema:
```prisma
datasource db {
  provider             = "postgresql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator client {
  provider        = "cargo prisma"
  output          = "../src/prisma.rs"
  previewFeatures = ["referentialIntegrity"]
}

model User {
  id String @id

  gamesPlayedAsWhite Game[] @relation("playerWhite")
  gamesPlayedAsBlack Game[] @relation("playerBlack")
}

model Game {
  id          String   @id @default(cuid())
  timePlayed  DateTime @default(now())
  is_finished Boolean  @default(false)

  white   User   @relation(fields: [whiteId], references: [id], name: "playerWhite")
  whiteId String

  black   User   @relation(fields: [blackId], references: [id], name: "playerBlack")
  blackId String

  currentPlayerId String

  whiteOutcome Outcome?

  blackOutcome Outcome?

  startingBoard   String
  inProgressBoard String
  finalBoard      String?

  moveList PieceMove[]
}

model PieceMove {
  id         String   @id @default(cuid())
  timePlayed DateTime @default(now())

  san String

  Game   Game   @relation(fields: [gameId], references: [id])
  gameId String
}

enum Outcome {
  WIN
  LOSS
  DRAW
}
```
